-- AlterTable
ALTER TABLE `PLAYERS` ADD COLUMN `cashier_id` VARCHAR(191) NULL;

-- CreateTable
CREATE TABLE `CASHIERS` (
    `id` VARCHAR(191) NOT NULL,
    `panel_id` INTEGER NOT NULL,
    `commission` DOUBLE NOT NULL,
    `earnings` DOUBLE NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PLAYERS` ADD CONSTRAINT `PLAYERS_cashier_id_fkey` FOREIGN KEY (`cashier_id`) REFERENCES `CASHIERS`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
