-- DropForeignKey
ALTER TABLE `AGENT_CONFIG` DROP FOREIGN KEY `USERS_ROOT_player_id_fkey`;

-- AddForeignKey
ALTER TABLE `AGENT_CONFIG` ADD CONSTRAINT `AGENT_CONFIG_player_id_fkey` FOREIGN KEY (`player_id`) REFERENCES `PLAYERS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- RedefineIndex
CREATE UNIQUE INDEX `AGENT_CONFIG_player_id_key` ON `AGENT_CONFIG`(`player_id`);
DROP INDEX `USERS_ROOT_player_id_key` ON `AGENT_CONFIG`;
