-- DropForeignKey
ALTER TABLE `BANK_ACCOUNTS` DROP FOREIGN KEY `BANK_ACCOUNTS_owner_id_fkey`;

-- AlterTable
ALTER TABLE `BANK_ACCOUNTS` MODIFY `bankAlias` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `BANK_ACCOUNTS` ADD CONSTRAINT `BANK_ACCOUNTS_player_id_fkey` FOREIGN KEY (`player_id`) REFERENCES `PLAYERS`(`panel_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
